application: three-strips-image-cropper
version: 3
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /js
  static_dir: js
- url: /stylesheets
  static_dir: stylesheets
- url: /.*
  script: cropyourimage.application
  
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest